# Generated by Django 2.0.7 on 2018-07-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20180712_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAVE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('vemail', models.EmailField(max_length=254, unique=True)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
