# Generated by Django 2.0.7 on 2018-07-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='text',
            field=models.CharField(max_length=10000),
        ),
    ]
